name: techeer-market

on:
  push:
    branches:
      - develop
      - main
  workflow_dispatch: # 브랜치 push 뿐만 아니라 수동 실행도 가능하게 해줌

jobs:
  build:
    runs-on: ubuntu-latest # 깃허브 액션 스크립트가 작동될 OS 환경 지정

    steps:
      - name: Checkout
        uses: actions/checkout@v2 # 프로젝트 코드를 check out

      - name: Set up JDK 11
        uses: actions/setup-java@v2  # 깃허브 액션에 사용할 자바 버전
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: access to secrets
        run: |
          echo "CLOUD_AWS_DB_HOST=${{secrets.CLOUD_AWS_DB_HOST}}"  >> src/main/resources/env.yml
          echo "CLOUD_AWS_DB_DATABASE_NAME=${{secrets.CLOUD_AWS_DB_DATABASE_NAME}}" >> src/main/resources/env.yml
          echo "CLOUD_AWS_DB_USERNAME=${{secrets.CLOUD_AWS_DB_USERNAME}}" >> src/main/resources/env.yml
          echo "CLOUD_AWS_DB_PASSWORD=${{secrets.CLOUD_AWS_DB_PASSWORD}}" >> src/main/resources/env.yml
          echo "CLOUD_AWS_S3_BUCKET_NAME=${{secrets.CLOUD_AWS_S3_BUCKET_NAME}}" >> src/main/resources/env.yml
          echo "CLOUD_AWS_S3_REGION=${{secrets.CLOUD_AWS_S3_REGION}}" >> src/main/resources/env.yml
          echo "CLOUD_AWS_ACCESS_KEY_ID=${{secrets.CLOUD_AWS_ACCESS_KEY_ID}}"  >> src/main/resources/env.yml
          echo "CLOUD_AWS_SECRET_ACCESS_KEY=${{secrets.CLOUD_AWS_SECRET_ACCESS_KEY}}" >> src/main/resources/env.yml

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew # gradle wrapper를 실행할 수 있도록 권한 부여
        shell: bash

      - name: Build with Gradle
        run: ./gradlew clean build # 프로젝트 빌드
        shell: bash

      - name: Get current time
        uses: 1466587594/get-current-time@v2  # 빌드 완료 시간 가져오기
        id: current-time
        uses: 1466587594/get-current-time@v2
        with:
          format: 'YYYY-MM-DDTHH-mm-ss'
          utcOffset: '+09:00'

      - name: Show Current Time
        run: echo "CurrentTime=${{steps.current-time.outputs.formattedTime}}" # 빌드 완료 시간 출력하기
        shell: bash
