name: techeer-market

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew clean build
        shell: bash

      - name: Get build time
        id: current-time
        uses: 1466587594/get-current-time@v2
        with:
          format: 'YYYY-MM-DDTHH-mm-ss'
          utcOffset: '+09:00'

      - name: Show Current Time
        run: echo "CurrentTime = ${{ steps.current-time.outputs.formattedTime }}"
        shell: bash
